---
- hosts: all
  remote_user: root

  tasks:
  - include_vars: users.yml
  - name: Creating users to Jump Server
    user: name="{{ item.username }}"
    with_items: "{{ users }}"

  - name: Placing SSH Key to Authorized Key
   authorized_key: user="{{ item.username }}" key="{{ lookup('file', '/etc/ansible/auth_key_store/khushal/authorized_keys.{{ item.username  }}.pub')}}"
    with_items: "{{ users }}"
  - lineinfile:
            dest: '/etc/sudoers'
            state: 'present'
            regexp: '^%wheel\s '
            insertafter: '^%wheel '
            line: '%{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
            validate: 'visudo -cf %s'
    with_items: "{{ users }}"

